language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: hGlhC7Xz3VNnDX0lqExloq6Ix3DFBqD4or4UXpWbmWZwP1te5cHfqGC/t41VWA6308p66mSZZR10xmlcSpanAYIHpM+vS02XAwKxGngX25/naRbpQ8sYQIxi7+KNBCYGEKV912nKqKt7vrIpz6NbrAu6OWnLgL2EpetZNr2w9N26XsuPWWgLMqqsVLrPH63eEaE01GjxR/rU4INmKYWBwGMix+6MgUkw2vnOHYD44rWo4ZkDh+yHe1ggzIqfA0RQrShl7hlenfr05eGLVE0IgV8xsPwsDgcsZHk7nIdDG/260w4p6N/dZeShB6sWXroO15DpIvltWjMdlwhHE1IAoXS4deR8xVt8zGfoGYX0sDXD20ZeD2k1u5wi/vtYf1CMPsIwIKFKZ1Dj4E6JbVZvDFuXNLHmcU9i6f71fkAeM4hi3sqPKvopUIyHqG2koVuA6n1qj6yHDebvLHplxiJRQD8OZVPGsU7pSlxZtkqjiREAnDibA6/qr5ZaeDWQbX77XxCcS6HNaiX6pREkLS2m7Liu6THNwnmpXo7b7PiqbOXbkgAtVOR3qOj8zzq6W7K2OknIMmsdo19JsH1cvFErwG8qZx7mE/zGb2+emFo/+4Y2jucLxlzv828cGICyClo56TGhGX8fxbDC+DQcnkZuoAAfNbD/DMjRTQe8k2kqsmA=
  app: floating-mesa-73214
  on:
    repo: thinkful-ei22/bgraham-ff-rankings-client
